### ISSUE TITLE
Add JWK and did:web support

### ISSUE THREAD

**Issue by jischr** [decentralized-identity/jwt-vc-presentation-profile#13]

**Comment by dwight-holman** [comment]
These were proposed for additional supported DID methods, so we should add them before the spec is "done".  

- did:jwk  https://github.com/quartzjer/did-jwk/blob/main/spec.md 
- did:web  https://w3c-ccg.github.io/did-method-web/

**Comment by Sakurann** [comment]
did:web has been agreed and done in PR #23

**Comment by Sakurann** [comment]
Could we potentially close this issue and have a separate issue discussing did:jwk vs did:key vs did:ebsi?
