### ISSUE TITLE
Conflict with current SIOPv2 spec and profile

### ISSUE THREAD

**Issue by dwight-holman** [decentralized-identity/jwt-vc-presentation-profile#18]
[SIOP says](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html#name-self-issued-id-token):

> iss is REQUIRED. in case of a self-issued ID token, this claim MUST be set to the value of the sub claim in the same ID Token.

Profile [currently says](https://identity.foundation/jwt-vc-presentation-profile/#id-token-validation):

> iss claim MUST be https://self-issued.me/v2/openid-vc.

**Comment by Sakurann** [comment]
yes, in current SIOPv2, iss==sub in the self-issued ID Token.

I think we should migrate to iss==sub once every implementer is ready. (potentially after interoping on the Issuance)

**Comment by Sakurann** [comment]
clarify that we use first implementer's draft of SIOPv2 and OpenID4VP and update the URL

**Comment by Sakurann** [comment]
PR #36
