### ISSUE TITLE
Wallets should not be required to check revocation status for linked domain credentials

### ISSUE THREAD

**Issue by dwight-holman** [decentralized-identity/jwt-vc-presentation-profile#24]
See title.

Easier for the issuers to remove them from .well-known endpoints.

**Comment by vlanard** [comment]
The ask here is to explicitly cite in the profile that this particular check is not required, so that we remove this identified instance of ambiguity that could lead to unneeded work. 
Let's tell implementers that they can assume that resolving well known did creds are unrevoked.

**Comment by dtmcg** [comment]
@nklomp to do a PR to clarify

**Comment by nklomp** [comment]
Forgot to add. If people do feel strongly about not having to do StatusList checks on DomainLinkage VCs. Then I would suggest to bring up the issue in the DID Well-known spec repo to begin with.

**Comment by Sakurann** [comment]
I just checked and I don't think anything in .well-known spec requires StatusList check in a DomainLinkage VC..?
https://identity.foundation/specs/did-configuration/

**Comment by nklomp** [comment]
No. So my suggestion is that I will add some non normative text stating that DomainLinkage VCs typically should not contain a StatusList and thus removal from the well-known location suffices

**Comment by dwight-holman** [comment]
Per @Sakurann 's comment, and https://identity.foundation/specs/did-configuration/#validation-of-domain-linkage-assertions , I think it's clearest to add language like

 > Validation of domain credentials by the wallet MUST follow the steps given in the _Well Known DID Configuration_ standard.  Additional checks, e.g. of revocation, are not required by this profile.

**Comment by nklomp** [comment]
I am not sure I follow the logic here. The response of @Sakurann is about .well-known spec not requiring StatusList checks. That is something different than saying it should not be required to validate if present.

Again, simply don't use a StatusList in the DomainLinkage credential to begin with. The issuer of the VC is in full control of that property being present or not. 

I really don't get this whole ticket to be hones. It doesn't make sense to me and reeks like an anti-pattern.

**Comment by dwight-holman** [comment]
> I really don't get this whole ticket to be honest. It doesn't make sense to me and reeks like an anti-pattern.

Sure, I'll elaborate.  My experience with decentralized identity is a bit unusual in that I'm not trying to write specifications and standards, I'm trying to solve a problem by making a running program implementing those standards.   As I read the standards, if I find myself asking questions arising from the combination of standards being referenced by the profile, I suggest modifications to the profile so that the right answer is obvious.

> Again, simply don't use a StatusList in the DomainLinkage credential to begin with. The issuer of the VC is in full control of that property being present or not.

Although the *issuer* is in control of the property being present, the *wallet* controls the interpretation of the credential.   The profile is saying in one place that credential revocation is handled by status lists, and in another that credentials are used for domain linkage.  

The relation of one to the other for a wallet implementation lead to several questions on my part, and adding a sentence saying one does not apply to the other answers them.   If that's not the answer we want?  Okay.  But something about the question would be helpful for people implementing wallets.

**Comment by nklomp** [comment]
Yes but then I suggest to add non-normative text that a DomainLinkage VC normally shouldn't contain a StatusList as in most circumstances simply removing it from the .well-known location suffices. I am really worried about a spec basically saying to not have to inspect something. The more exceptions like these you make the more things that can go wrong.
Typically a wallet will have StatusList support anyway, as you also want to be aware of VCs you poses which might have been exposed. Or VCs you interpret from other parties during an exchange

**Comment by dwight-holman** [comment]
The standard, as linked above, has a specific and limited set of checks it does, none of which are revocation checks.    Adding a revocation check diverges from the specs we're referencing. 

Perhaps a two-sentence reminder that one does not apply to the other is out of scope for the profile.   We can close this with no corresponding changes to the profile if that's the case.

**Comment by nklomp** [comment]
Yes, but CredentialStatus is part of the VC-Data model and it is not explicitly excluded from the interop profile. Actually the whole revocation chapter is about it. https://identity.foundation/jwt-vc-presentation-profile/#revocation So then it might become confusing for some people why certain parts of the spec require credentialStatus checks to be implemented but then another part of the spec is saying "just ignore it here".


To not make it really explicit, I suggest some non-normative text. Something to the extent of:

_Since Domain Linkage Credentials are being managed by the Verifier/RP by updating the DID Configuration Resource directly, the usage of a credentialStatus property in a Domain Linkage Credential typically is of little use._

**Comment by nklomp** [comment]
> Per @Sakurann 's comment, and https://identity.foundation/specs/did-configuration/#validation-of-domain-linkage-assertions , I think it's clearest to add language like
> 
> > Validation of domain credentials by the wallet MUST follow the steps given in the _Well Known DID Configuration_ standard.  Additional checks, e.g. of revocation, are not required by this profile.

Sorry missed this comment. Maybe merging both of our suggestions a bit might be the solution 😅

**Comment by nklomp** [comment]
I merged both texts, but added a little text about expiration. Thas has to do with the well-known DIDs normatively mentioning that expirationDate has to be present: https://identity.foundation/.well-known/resources/did-configuration/#domain-linkage-credential.

> Validation of domain credentials by the wallet MUST follow the steps given in the Well Known DID Configuration standard. Additional checks, e.g. of revocation, are not required by this profile. Since Domain Linkage Credentials are being managed by the Verifier/RP by updating the DID Configuration Resource directly, the usage of a credentialStatus property for revocation in a Domain Linkage Credential typically is of little use. Expiration of the Domain Linkage Credential does need to be taken into account.

**Comment by Sakurann** [comment]
I agree with the proposed text above

**Comment by jischr** [comment]
consensus: following steps in well known did configuration and does not included status list in credential.

**Comment by nklomp** [comment]
Ignore the above mention from the PR. I used the wrong issue nr by accident

**Comment by nklomp** [comment]
Updated PR with latest comment. Should be ready for approval
