### ISSUE TITLE
Why is the custom protocol `openid-vc://` instead of `openid://`

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/jwt-vc-presentation-profile#33]
SIOPv2 declares the custom scheme as `openid:` however this profile declares it as `openid-vc:`

**Comment by tplooker** [comment]
Hey there is still active conversation on this topic see [here](https://bitbucket.org/openid/connect/pull-requests/226)

**Comment by Sakurann** [comment]
SIOP v2 reserves the usage of `openid://` only with the specific set of wallet's metadata. so implementations that use metadata diverging with static metadata tied to openid:// need to use other custom URL scheme. It could be anything. this document just picked openid-vc:

**Comment by Sakurann** [comment]
@tplooker the conversation in the bitbucket you are pointing to is the custom URL scheme used in issuance when there is no scheme defined elsewhere or pre-registered. issuance profiles like this one can define other custom url schemes.
