### ISSUE TITLE
Clarify the version of PE used

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/jwt-vc-presentation-profile#37]
I believe this profile uses basic PEv1 capabilities + only SIOP optimized capabilities in PEv2 - which would be a specific commit within PE v2

**Comment by dtmcg** [comment]
@Sakurann will add clarification in a pr

**Comment by Sakurann** [comment]
It's PE v1 adding only the ability to add formats to input descriptors: 

> The [Input Descriptor Object](https://identity.foundation/presentation-exchange/#term:input-descriptor-object) MAY contain a format property. If present, its value MUST be an object with one or more properties matching the registered [Claim Format Designations](https://identity.foundation/presentation-exchange/#claim-format-designations) (e.g., jwt, jwt_vc, jwt_vp, etc.). This format property is identical in value signature to the top-level format object, but can be used to specifically constrain submission of a single input to a subset of formats or algorithms.
