### ISSUE TITLE
Update text to Presentation Exchange 2.0

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/jwt-vc-presentation-profile#57]
The linked "OpenID4VP" document refers to Presentation Exchange 2.0 rather than Presentation Exchange 1.0.

**Comment by jischr** [comment]
@dtmcg proposes to version this profile with PE v1  (as a v0.1) and then merge PE V2 as a living doc (for v1)

**Comment by jischr** [comment]
@jischr to make a new issue to capture above
